import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { renderMonthlyBudget, renderMonthlyBudgetAmountSheet, renderMonthlyBudgetRowSheet } from '../src/screens/monthlyBudget.js';
import { createMonthlyBudgetDraft, updateMonthlyBudgetRow } from '../src/services/budgetPlanningService.js';

const state = { categories: [{ name: 'Hogar <script>', subcategories: ['Agua', 'Alquiler'] }], accounts: [{ name: 'Caja' }], budgets: [], ui: {} };
state.ui.monthlyBudgetDraft = createMonthlyBudgetDraft(state, '2026-10', { category: 'Hogar <script>' });
const rent = state.ui.monthlyBudgetDraft.rows.find(row => row.subcategory === 'Alquiler');
const water = state.ui.monthlyBudgetDraft.rows.find(row => row.subcategory === 'Agua');
state.ui.monthlyBudgetDraft = updateMonthlyBudgetRow(state.ui.monthlyBudgetDraft, rent.draftId, { amount: 200 });
state.ui.monthlyBudgetDraft = updateMonthlyBudgetRow(state.ui.monthlyBudgetDraft, water.draftId, { amount: 50 });
let markup = renderMonthlyBudget(state);
assert.match(markup, /Octubre 2026/);
assert.match(markup, /Septiembre 2026/);
assert.match(markup, /data-monthly-budget-save/);
assert.match(markup, /data-monthly-budget-total/);
assert.match(markup, /250\.00/);
assert.match(markup, /data-monthly-budget-amount=/);
assert.match(markup, /data-monthly-budget-edit=/);
assert.match(markup, /data-monthly-budget-delete=/);
assert.match(markup, /aria-expanded="true"/);
assert.match(markup, /Hogar &lt;script&gt;/);
assert.doesNotMatch(markup, /<script>|<select|type="month"/);
state.ui.monthlyBudgetMonthPicker = true;
state.ui.monthlyBudgetPickerYear = 2027;
markup = renderMonthlyBudget(state);
assert.match(markup, /data-monthly-budget-month="2027-01"/);
assert.match(markup, /data-monthly-budget-year-step="-1"/);
const amountSheet = renderMonthlyBudgetAmountSheet(state, water);
assert.match(amountSheet, /data-keypad/);
assert.match(amountSheet, /data-monthly-budget-amount-apply/);
assert.match(amountSheet, /data-monthly-budget-amount-cancel/);
const editSheet = renderMonthlyBudgetRowSheet(state, water);
assert.match(editSheet, /data-monthly-budget-pick="account"/);
assert.match(editSheet, /data-monthly-budget-row-apply/);
assert.match(editSheet, /data-monthly-budget-row-cancel/);
assert.match(editSheet, /data-monthly-budget-row-amount-open/);
assert.doesNotMatch(editSheet, /<select/);
assert.equal(renderMonthlyBudget({ ui: {} }), '');
const css = await readFile(new URL('../styles/budgetPlanning.css', import.meta.url), 'utf8');
assert.match(css, /min-height:\s*44px/);
assert.match(css, /overflow-y:\s*auto/);
console.log('Monthly budget UI tests passed');
